CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE  IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,

    username TEXT NOT NULL UNIQUE,
    email CITEXT NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);